// swift-tools-version: 6.4
import PackageDescription

let package = Package(
    name: "ups-monitor-macos",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "UPSCore", targets: ["UPSCore"]),
        .library(name: "UPSEnergy", targets: ["UPSEnergy"]),
        .library(name: "ApplePowerSource", targets: ["ApplePowerSource"]),
        .library(name: "NUTData", targets: ["NUTData"]),
        .library(name: "NUTClient", targets: ["NUTClient"]),
        .library(name: "UPSModel", targets: ["UPSModel"]),
        .library(name: "UPSHistory", targets: ["UPSHistory"]),
        .library(name: "UPSRuntime", targets: ["UPSRuntime"]),
        .library(name: "UPSMonitorUI", targets: ["UPSMonitorUI"]),
        .library(name: "UPSWidgetData", targets: ["UPSWidgetData"]),
        .library(name: "UPSWidgetUI", targets: ["UPSWidgetUI"]),
        .library(name: "UPSWidgetBridge", targets: ["UPSWidgetBridge"]),
        .executable(name: "ups-probe", targets: ["UPSProbe"]),
        .executable(name: "ups-render-probe", targets: ["UPSRenderProbe"]),
    ],
    targets: [
        .target(name: "UPSCore"),
        .target(name: "UPSEnergy", dependencies: ["UPSModel"]),
        .target(name: "ApplePowerSource", dependencies: ["UPSCore"], linkerSettings: [.linkedFramework("IOKit")]),
        .target(name: "NUTData"),
        .target(name: "NUTClient", dependencies: ["NUTData"]),
        .target(name: "UPSModel", dependencies: ["UPSCore", "NUTData"]),
        .target(name: "UPSHistory", dependencies: ["UPSModel"], linkerSettings: [.linkedLibrary("sqlite3")]),
        .target(name: "UPSRuntime", dependencies: ["UPSCore", "ApplePowerSource", "UPSModel", "NUTClient", "NUTData"]),
        .target(name: "UPSMonitorUI", dependencies: ["UPSModel", "UPSEnergy"]),
        .target(name: "UPSWidgetData", dependencies: ["UPSModel"]),
        .target(name: "UPSWidgetUI", dependencies: ["UPSWidgetData", "UPSModel", "UPSMonitorUI"]),
        .target(name: "UPSWidgetBridge", dependencies: ["UPSWidgetData", "UPSModel"], linkerSettings: [.linkedFramework("Security")]),
        .target(name: "UPSAppHost", dependencies: ["ApplePowerSource", "UPSHistory", "UPSModel", "UPSMonitorUI", "UPSRuntime", "UPSWidgetData", "UPSWidgetBridge", "NUTClient", "UPSEnergy"],
                path: "App", exclude: ["Info.plist", "UPSMonitorApp.swift", "Shared.entitlements"]),
        .executableTarget(name: "UPSProbe", dependencies: ["UPSCore", "ApplePowerSource", "UPSRuntime", "UPSModel"]),
        .executableTarget(name: "UPSRenderProbe", dependencies: ["UPSModel", "UPSEnergy", "UPSMonitorUI", "UPSWidgetData", "UPSWidgetUI"],
                          linkerSettings: [.linkedFramework("AppKit"), .linkedFramework("ImageIO")]),
        .testTarget(name: "UPSCoreTests", dependencies: ["UPSCore"]),
        .testTarget(name: "UPSEnergyTests", dependencies: ["UPSEnergy", "UPSModel"]),
        .testTarget(name: "ApplePowerSourceTests", dependencies: ["ApplePowerSource", "UPSCore"]),
        .testTarget(name: "NUTDataTests", dependencies: ["NUTData"]),
        .testTarget(name: "NUTClientTests", dependencies: ["NUTClient", "NUTData", "UPSRuntime", "UPSModel"]),
        .testTarget(name: "UPSModelTests", dependencies: ["UPSModel", "UPSCore", "NUTData"]),
        .testTarget(name: "UPSHistoryTests", dependencies: ["UPSHistory", "UPSModel"]),
        .testTarget(name: "UPSRuntimeTests", dependencies: ["UPSRuntime", "UPSModel", "UPSCore", "NUTClient", "NUTData"]),
        .testTarget(name: "UPSMonitorUITests", dependencies: ["UPSMonitorUI", "UPSModel", "UPSEnergy"]),
        .testTarget(name: "UPSAppHostTests", dependencies: ["UPSAppHost", "UPSModel", "UPSHistory", "UPSWidgetData", "UPSWidgetBridge", "UPSMonitorUI", "UPSEnergy"]),
        .testTarget(name: "UPSWidgetDataTests", dependencies: ["UPSWidgetData", "UPSModel"]),
        .testTarget(name: "UPSWidgetUITests", dependencies: ["UPSWidgetUI", "UPSWidgetData", "UPSModel"]),
        .testTarget(name: "UPSWidgetBridgeTests", dependencies: ["UPSWidgetBridge", "UPSWidgetData", "UPSModel"]),
    ]
)
